modLoader = "kotlinforforge"

loaderVersion = "[4,)" # the loader is kotlin for forge
license = "GNU-LGPL-3.0"
issueTrackerURL = "https://github.com/lilmods/horse-stats/issues"

[[mods]]
modId = "horsestatsmod"
version = "1.0.0"
displayName = "HorseStats"
authors = "lilgallon"
description = '''
A lightweight mod that shows the hidden horses' stats (health, jump height, speed, and slots for Llamas)
'''
updateJSONURL="https://raw.githubusercontent.com/lilmods/horse-stats/main/updates.json"
logoFile="icon.png"
[[dependencies.horsestatsmod]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "CLIENT"
[[dependencies.horsestatsmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "CLIENT"
